import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Why Choose Us | Medical Weight Loss That's Actually Medical",
  description:
    "Discover what makes Precision Weight + Wellness different: board-certified physician Dr. Libby Rhee, personalized 1:1 care, a real NYC medical office, and treatment plans created by a doctor — not an algorithm.",
};

const differentiators = [
  {
    title: "Your doctor has a name",
    desc: "Dr. Libby Rhee, DO, MS, FAAD — board-certified, Mount Sinai clinical instructor, and thousands of five-star patient reviews. She does not hand your case to an algorithm or a nurse practitioner. She is your physician from consultation through maintenance.",
  },
  {
    title: "One physician, one patient, one plan",
    desc: "Every treatment protocol is created by Dr. Rhee personally after reviewing your medical history, lab results, and goals. No templated questionnaires. No auto-generated protocols. Medicine the way it was meant to be practiced.",
  },
  {
    title: "A real medical office, not just an app",
    desc: "Our Upper East Side practice at 110 E 60th Street offers in-person consultations in a private, comfortable setting. Telehealth is available for follow-ups and out-of-state patients, but you always have the option to be seen face-to-face.",
  },
  {
    title: "Medical credibility you can verify",
    desc: "Board-certified by the American Board of Dermatology. Fellow of the American Academy of Dermatology. Clinical Instructor at Mount Sinai Icahn School of Medicine. These are not marketing claims — they are verifiable credentials.",
  },
  {
    title: "The whole person, not just the prescription",
    desc: "GLP-1 medication is the foundation, but your plan includes nutritional guidance, lifestyle modification, metabolic monitoring, and behavioral support. We treat the person, not just the number on the scale.",
  },
  {
    title: "No algorithms. No chatbots. No surprises.",
    desc: "Every decision about your care is made by a physician, not generated by software. When you message our office, a human responds. When your dose needs adjusting, Dr. Rhee makes that call.",
  },
];

const contrasts = [
  {
    label: "Your physician",
    elsewhere:
      "Assigned provider you have never met, or algorithm-generated care plan",
    here: "Dr. Libby Rhee — your physician from day one through maintenance, board-certified with Mount Sinai affiliation",
  },
  {
    label: "Your care plan",
    elsewhere:
      "Templated protocol based on a short online questionnaire",
    here: "Individually designed treatment plan based on comprehensive health assessment, lab review, and in-person evaluation",
  },
  {
    label: "Medication management",
    elsewhere:
      "Auto-refill prescriptions with periodic check-in surveys",
    here: "Physician-monitored dosing with regular adjustments based on your response, labs, and side effect profile",
  },
  {
    label: "Support model",
    elsewhere:
      "Chat-based coaching, community forums, or AI-generated responses",
    here: "Direct access to your physician and care team, secure messaging with human response, priority scheduling",
  },
  {
    label: "Setting",
    elsewhere:
      "App-only or telehealth-only — no option to be seen in person",
    here: "Private Upper East Side medical office with in-person and telehealth flexibility",
  },
  {
    label: "Continuity",
    elsewhere:
      "Different provider each visit, or no provider at all",
    here: "Same physician, every visit — Dr. Rhee personally monitors your entire journey",
  },
];

const rightFor = [
  "You want a named physician managing your care, not an app or algorithm",
  "You value in-person medical evaluations, not just telehealth questionnaires",
  "You have tried other weight loss approaches without lasting success",
  "You want a treatment plan tailored to your specific biology and health history",
  "You prefer a private, premium medical setting",
];

const otherOption = [
  "You are looking for the lowest-cost option above all else",
  "You prefer a fully self-directed app-based program",
  "You do not need or want regular physician involvement",
  "You are looking for medication only, without comprehensive medical oversight",
];

export default function WhyUsPage() {
  return (
    <>
      {/* Hero */}
      <section className="pt-36 pb-24 bg-cream">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <p className="text-[11px] tracking-[0.3em] uppercase text-gold mb-6">
            The Precision Difference
          </p>
          <h1
            className="font-serif text-5xl md:text-6xl leading-[1.08] tracking-tight text-soft-black"
            style={{ textWrap: "balance" }}
          >
            What changes when your doctor actually{" "}
            <span className="text-gold">knows your name</span>
          </h1>
          <p className="mt-8 text-lg text-neutral-500 max-w-2xl mx-auto leading-relaxed">
            Most weight loss programs are built on algorithms, chatbots, and
            one-size-fits-all protocols. Precision Weight + Wellness is built on
            something different: a named physician, a real medical office, and a
            plan created for you alone.
          </p>
        </div>
      </section>

      {/* The Problem */}
      <section className="py-32 bg-white">
        <div className="max-w-4xl mx-auto px-6">
          <div className="text-center mb-16">
            <p className="text-[11px] tracking-[0.3em] uppercase text-gold mb-4">
              The landscape today
            </p>
            <h2
              className="font-serif text-4xl md:text-5xl tracking-tight text-soft-black"
              style={{ textWrap: "balance" }}
            >
              Weight loss has become an industry. We think it should be medicine.
            </h2>
          </div>
          <div className="space-y-6 text-neutral-500 leading-relaxed max-w-3xl mx-auto">
            <p>
              Telehealth startups dispense medications after a five-minute
              questionnaire. Subscription apps assign you to a chat-based
              &ldquo;coach&rdquo; you will never meet. Celebrity-endorsed
              programs sell community when what you need is clinical expertise.
            </p>
            <p>
              These approaches work for some people. But if you want a physician
              who personally reviews your labs, adjusts your medication, and
              knows your name — not your user ID — you need a different model
              entirely.
            </p>
            <p className="text-soft-black font-medium">
              That is what Precision Weight + Wellness was built to be.
            </p>
          </div>
        </div>
      </section>

      {/* Six Differentiators */}
      <section className="py-32 bg-cream">
        <div className="max-w-7xl mx-auto px-6">
          <div className="max-w-xl mb-16">
            <p className="text-[11px] tracking-[0.3em] uppercase text-gold mb-4">
              Why patients choose us
            </p>
            <h2
              className="font-serif text-4xl md:text-5xl tracking-tight text-soft-black"
              style={{ textWrap: "balance" }}
            >
              Six things you will not find anywhere else
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {differentiators.map((d, i) => (
              <div
                key={d.title}
                className={`bg-white p-10 rounded-2xl transition-all duration-350 ease-[cubic-bezier(0.16,1,0.3,1)] hover:translate-y-[-2px] hover:shadow-[0_16px_40px_-12px_rgba(201,169,110,0.08)] ${
                  i === 0 ? "md:col-span-2" : ""
                }`}
              >
                <h3
                  className={`font-serif text-soft-black ${
                    i === 0 ? "text-2xl" : "text-xl"
                  }`}
                >
                  {d.title}
                </h3>
                <p
                  className={`mt-4 text-neutral-500 leading-relaxed ${
                    i === 0 ? "text-base max-w-3xl" : "text-sm"
                  }`}
                >
                  {d.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Side-by-Side Comparison */}
      <section className="py-32 bg-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="max-w-xl mb-16">
            <p className="text-[11px] tracking-[0.3em] uppercase text-gold mb-4">
              A different standard of care
            </p>
            <h2
              className="font-serif text-4xl md:text-5xl tracking-tight text-soft-black"
              style={{ textWrap: "balance" }}
            >
              What most programs offer vs. what we believe you deserve
            </h2>
          </div>
          <div className="space-y-0 divide-y divide-neutral-100">
            {contrasts.map((c) => (
              <div
                key={c.label}
                className="grid grid-cols-1 md:grid-cols-[200px_1fr_1fr] gap-6 md:gap-10 py-8 first:pt-0 last:pb-0"
              >
                <p className="font-serif text-lg text-soft-black md:pt-1">
                  {c.label}
                </p>
                <div>
                  <p className="text-xs tracking-[0.15em] uppercase text-neutral-300 mb-2">
                    Elsewhere
                  </p>
                  <p className="text-sm text-neutral-400 leading-relaxed">
                    {c.elsewhere}
                  </p>
                </div>
                <div>
                  <p className="text-xs tracking-[0.15em] uppercase text-gold mb-2">
                    At Precision Weight + Wellness
                  </p>
                  <p className="text-sm text-soft-black leading-relaxed">
                    {c.here}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Credentials Bar */}
      <section className="bg-soft-black py-16">
        <div className="max-w-5xl mx-auto px-6 grid grid-cols-2 sm:grid-cols-4 gap-10 text-center">
          {[
            { value: "DO, MS, FAAD", label: "Board-Certified Credentials" },
            { value: "Mount Sinai", label: "Clinical Instructor" },
            { value: "1:1", label: "Every Patient Sees Dr. Rhee" },
            { value: "NYC", label: "In-Person Upper East Side" },
          ].map((s) => (
            <div key={s.label}>
              <p className="font-serif text-2xl md:text-3xl text-gold">
                {s.value}
              </p>
              <p className="text-[11px] tracking-[0.2em] uppercase text-neutral-400 mt-3">
                {s.label}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Testimonial Spotlight */}
      <section className="py-32 bg-cream">
        <div className="max-w-7xl mx-auto px-6">
          <div className="max-w-xl mb-16">
            <p className="text-[11px] tracking-[0.3em] uppercase text-gold mb-4">
              In their words
            </p>
            <h2
              className="font-serif text-4xl md:text-5xl tracking-tight text-soft-black"
              style={{ textWrap: "balance" }}
            >
              What our patients notice first
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Featured testimonial */}
            <div className="bg-white p-10 md:p-14 rounded-2xl md:row-span-2 flex flex-col justify-center transition-all duration-350 ease-[cubic-bezier(0.16,1,0.3,1)] hover:shadow-[0_16px_40px_-12px_rgba(201,169,110,0.08)]">
              <div className="flex gap-1 text-gold mb-6">
                {[...Array(5)].map((_, j) => (
                  <span key={j} className="text-lg">
                    &#9733;
                  </span>
                ))}
              </div>
              <p className="text-lg text-neutral-600 leading-relaxed italic">
                &ldquo;I&apos;ve tried everything — keto, intermittent fasting,
                personal trainers. Nothing worked long-term until I started GLP-1
                therapy with Dr. Rhee. This is different because it actually
                addresses the root cause.&rdquo;
              </p>
              <div className="mt-8">
                <p className="font-medium text-soft-black">Mark S.</p>
                <p className="text-xs text-neutral-400 mt-1">New York, NY</p>
              </div>
              <p className="mt-3 text-[10px] tracking-wide uppercase text-neutral-300">
                Placeholder testimonial
              </p>
            </div>
            {/* Supporting testimonials */}
            {[
              {
                quote:
                  "My A1C has dropped significantly since starting the program. Dr. Rhee coordinates with my endocrinologist, which gives me peace of mind that all aspects of my health are being considered.",
                name: "Patricia H.",
                city: "New York, NY",
              },
              {
                quote:
                  "Dr. Rhee took the time to understand my health history and created a plan that actually works. The ongoing support has been incredible — I never feel like I'm doing this alone.",
                name: "Sarah M.",
                city: "New York, NY",
              },
            ].map((t, i) => (
              <div
                key={i}
                className="bg-white p-8 rounded-2xl transition-all duration-350 ease-[cubic-bezier(0.16,1,0.3,1)] hover:shadow-[0_16px_40px_-12px_rgba(201,169,110,0.08)]"
              >
                <div className="flex gap-1 text-gold mb-4">
                  {[...Array(5)].map((_, j) => (
                    <span key={j}>&#9733;</span>
                  ))}
                </div>
                <p className="text-sm text-neutral-600 leading-relaxed italic">
                  &ldquo;{t.quote}&rdquo;
                </p>
                <div className="mt-5">
                  <p className="text-sm font-medium text-soft-black">
                    {t.name}
                  </p>
                  <p className="text-xs text-neutral-400">{t.city}</p>
                </div>
                <p className="mt-2 text-[10px] tracking-wide uppercase text-neutral-300">
                  Placeholder testimonial
                </p>
              </div>
            ))}
          </div>
          <div className="mt-12">
            <Link
              href="/testimonials"
              className="inline-block text-sm tracking-wide uppercase text-gold hover:text-gold-dark transition-all duration-350 ease-[cubic-bezier(0.16,1,0.3,1)]"
            >
              See all testimonials &rarr;
            </Link>
          </div>
        </div>
      </section>

      {/* Is This Right For You? */}
      <section className="py-32 bg-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="max-w-3xl mx-auto text-center mb-16">
            <p className="text-[11px] tracking-[0.3em] uppercase text-gold mb-4">
              Is this right for you?
            </p>
            <h2
              className="font-serif text-4xl md:text-5xl tracking-tight text-soft-black"
              style={{ textWrap: "balance" }}
            >
              We are not the right fit for everyone — and that is by design
            </h2>
            <p className="mt-6 text-neutral-500 leading-relaxed">
              Precision Weight + Wellness is a boutique medical practice, not a
              volume-based subscription service. We intentionally keep our
              patient panel small so that Dr. Rhee can give every patient the
              attention they deserve.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-5xl mx-auto">
            <div className="bg-cream p-10 rounded-2xl">
              <h3 className="font-serif text-xl text-soft-black mb-6">
                This might be right for you if&hellip;
              </h3>
              <ul className="space-y-4">
                {rightFor.map((item) => (
                  <li key={item} className="flex gap-3 text-sm text-neutral-600 leading-relaxed">
                    <span className="text-gold mt-0.5 shrink-0">&#10003;</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-cream p-10 rounded-2xl">
              <h3 className="font-serif text-xl text-soft-black mb-6">
                You might prefer another option if&hellip;
              </h3>
              <ul className="space-y-4">
                {otherOption.map((item) => (
                  <li key={item} className="flex gap-3 text-sm text-neutral-500 leading-relaxed">
                    <span className="text-neutral-300 mt-0.5 shrink-0">&mdash;</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="relative py-32 bg-soft-black text-center overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gold/5 rounded-full blur-3xl pointer-events-none" />
        <div className="relative max-w-2xl mx-auto px-6">
          <h2
            className="font-serif text-4xl md:text-5xl tracking-tight text-white"
            style={{ textWrap: "balance" }}
          >
            Experience the difference for yourself
          </h2>
          <p className="mt-6 text-neutral-400 leading-relaxed">
            Schedule a consultation with Dr. Rhee to see what personalized,
            physician-led weight management looks like.
          </p>
          <div className="mt-10 flex flex-wrap justify-center gap-4">
            <Link
              href="/book"
              className="bg-gold hover:bg-gold-dark text-white text-sm tracking-wide uppercase px-10 py-4 rounded-full transition-all duration-350 ease-[cubic-bezier(0.16,1,0.3,1)] hover:translate-y-[-1px] hover:shadow-[0_8px_24px_-8px_rgba(201,169,110,0.4)]"
            >
              Book Your Consultation
            </Link>
            <Link
              href="/eligibility"
              className="border border-neutral-600 text-neutral-300 hover:border-gold hover:text-gold text-sm tracking-wide uppercase px-10 py-4 rounded-full transition-all duration-350 ease-[cubic-bezier(0.16,1,0.3,1)] hover:translate-y-[-1px]"
            >
              Check Your Eligibility
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
