-- PW+W clinic (local PGlite / prod Neon). Ids generated in app.

create table if not exists patients (
  id text primary key,
  email text unique,
  phone text,
  name text not null,
  dob date,
  ema_patient_id text,
  created_at timestamptz not null default now()
);

create table if not exists users (
  id text primary key,
  email text unique not null,
  password_hash text not null,
  role text not null check (role in ('patient','staff','doctor')),
  patient_id text references patients(id),
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists memberships (
  id text primary key,
  patient_id text not null references patients(id),
  tier text not null check (tier in ('essential','premium','concierge')),
  status text not null check (status in ('lead','active','paused','canceled')),
  started_on date,
  cycle_anchor date,
  billing_note text,
  provider text,
  provider_customer_id text,
  provider_subscription_id text
);

create table if not exists vitals (
  id text primary key,
  patient_id text not null references patients(id),
  recorded_at timestamptz not null default now(),
  source text not null check (source in ('patient','staff','device')),
  weight_lb numeric,
  waist_in numeric,
  systolic int,
  diastolic int,
  notes text
);

create table if not exists protocol_state (
  patient_id text primary key references patients(id),
  drug text,
  current_dose text,
  next_action text check (next_action in ('hold','stay','titrate','refill_due')),
  next_action_on date,
  updated_by text references users(id),
  updated_at timestamptz not null default now()
);

create table if not exists check_ins (
  id text primary key,
  patient_id text not null references patients(id),
  week_of date not null,
  feeling int,
  meds_taken text,
  side_effects text,
  diet int,
  exercise_days int,
  sleep int,
  energy int,
  challenge text,
  went_well text,
  questions text
);

create table if not exists visits (
  id text primary key,
  patient_id text not null references patients(id),
  starts_at timestamptz not null,
  modality text not null check (modality in ('in_person','remote')),
  status text not null check (status in ('requested','scheduled','completed','canceled','no_show')),
  video_url text,
  ema_appointment_id text,
  notes text
);

create table if not exists eligibility_runs (
  id text primary key,
  patient_id text references patients(id),
  bmi numeric,
  conditions jsonb,
  insurer text,
  qualifies boolean,
  created_at timestamptz not null default now()
);

create table if not exists audit_events (
  id bigint generated by default as identity primary key,
  actor_id text,
  patient_id text,
  action text not null,
  payload jsonb,
  created_at timestamptz not null default now()
);

create table if not exists leads (
  id text primary key,
  email text,
  stage text not null,
  payload jsonb,
  patient_id text,
  updated_at timestamptz not null default now()
);

create table if not exists tasks (
  id text primary key,
  kind text not null,
  priority int not null default 0,
  status text not null default 'open',
  patient_id text,
  title text not null,
  body text,
  due_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists lab_panels (
  id text primary key,
  patient_id text not null,
  collected_on date not null,
  status text not null default 'resulted',
  notes text
);

create table if not exists lab_results (
  id text primary key,
  panel_id text not null,
  analyte text not null,
  value numeric,
  unit text,
  ref_low numeric,
  ref_high numeric,
  flag text
);

create table if not exists visit_notes (
  id text primary key,
  visit_id text not null,
  body text not null,
  prefill_sources jsonb,
  signed_at timestamptz,
  signed_by text
);

create table if not exists clinic_config (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
